* Highlight only section headings

This package teaches ~outline-minor-mode~ to highlight section
headings, *without* also highlighting top-level s-expressions.

To highlight only section headings forgo setting the built-in
~outline-minor-mode-highlight~ to ~append~, or another non-nil value.
Instead enable the equivalent feature provided by this package:

#+begin_src emacs-lisp
  (use-package outline-minor-faces
    :after outline
    :config (add-hook 'outline-minor-mode-hook
                      #'outline-minor-faces-mode))
#+end_src

For non-lisp major modes the highlighting provided by this package
and by the built-in support is essentiall the same, i.e., the first
lines of top-level expressions *are* highlighted.

This package also defines separate faces for use in the minor mode.
These faces are what gave this package its name, but nowadays they
inherit from the built-in faces by default, and are preserved mostly
for historic reasons, i.e., to avoid having to rename this package.

#+html: <br><br>
#+html: <a href="https://github.com/tarsius/outline-minor-faces/actions/workflows/compile.yml"><img alt="Compile" src="https://github.com/tarsius/outline-minor-faces/actions/workflows/compile.yml/badge.svg"/></a>
#+html: <a href="https://stable.melpa.org/#/outline-minor-faces"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/outline-minor-faces-badge.svg"/></a>
#+html: <a href="https://melpa.org/#/outline-minor-faces"><img alt="MELPA" src="https://melpa.org/packages/outline-minor-faces-badge.svg"/></a>
